// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Connect4$Game_project = require("./Connect4.bs.js");

function AIPlayer(MyGame) {
  var nextMove = function (s) {
    return List.hd(Curry._1(MyGame.legalMoves, s));
  };
  return {
          PlayerGame: MyGame,
          nextMove: nextMove,
          playerName: ""
        };
}

var MyGame_stringOfPlayer = Connect4$Game_project.Connect4.stringOfPlayer;

var MyGame_stringOfState = Connect4$Game_project.Connect4.stringOfState;

var MyGame_stringOfMove = Connect4$Game_project.Connect4.stringOfMove;

var MyGame_initialState = Connect4$Game_project.Connect4.initialState;

var MyGame_legalMoves = Connect4$Game_project.Connect4.legalMoves;

var MyGame_gameStatus = Connect4$Game_project.Connect4.gameStatus;

var MyGame_nextState = Connect4$Game_project.Connect4.nextState;

var MyGame_moveOfString = Connect4$Game_project.Connect4.moveOfString;

var MyGame_estimateValue = Connect4$Game_project.Connect4.estimateValue;

var MyGame = {
  stringOfPlayer: MyGame_stringOfPlayer,
  stringOfState: MyGame_stringOfState,
  stringOfMove: MyGame_stringOfMove,
  initialState: MyGame_initialState,
  legalMoves: MyGame_legalMoves,
  gameStatus: MyGame_gameStatus,
  nextState: MyGame_nextState,
  moveOfString: MyGame_moveOfString,
  estimateValue: MyGame_estimateValue
};

function nextMove(s) {
  return List.hd(Curry._1(Connect4$Game_project.Connect4.legalMoves, s));
}

var TestAIPlayer = {
  PlayerGame: MyGame,
  nextMove: nextMove,
  playerName: ""
};

var TestGame;

var MyAIPlayer = TestAIPlayer;

exports.AIPlayer = AIPlayer;
exports.TestGame = TestGame;
exports.TestAIPlayer = TestAIPlayer;
exports.MyAIPlayer = MyAIPlayer;
/* Connect4-Game_project Not a pure module */
