// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var CS17SetupGame$Game_project = require("./CS17SetupGame.bs.js");

function stringOfPlace(param) {
  switch (param) {
    case /* Red */0 :
        return "\x1b[31m--Red---\x1b[0m";
    case /* Yellow */1 :
        return "\x1b[33m-Yellow-\x1b[0m";
    case /* None */2 :
        return "\x1b[32m--None--\x1b[0m";
    
  }
}

var horzFlip = List.rev;

function transpose(matrixIn) {
  if (!matrixIn) {
    return Pervasives.failwith("A matrix cannot be 0-dimensional");
  }
  var match = matrixIn.hd;
  if (match) {
    if (match.tl) {
      return {
              hd: List.map(List.hd, matrixIn),
              tl: transpose(List.map(List.tl, matrixIn))
            };
    } else {
      return {
              hd: List.flatten(matrixIn),
              tl: /* [] */0
            };
    }
  } else {
    return Pervasives.failwith("A matrix cannot be 0-dimensional");
  }
}

function mainDiagonal(inMatrix) {
  if (!inMatrix) {
    return Pervasives.failwith("error_mainDiagonal");
  }
  var match = inMatrix.hd;
  if (!match) {
    return Pervasives.failwith("error_mainDiagonal");
  }
  var item = match.hd;
  if (!match.tl) {
    return {
            hd: item,
            tl: /* [] */0
          };
  }
  var tl = inMatrix.tl;
  if (tl) {
    return {
            hd: item,
            tl: mainDiagonal(List.map(List.tl, tl))
          };
  } else {
    return {
            hd: item,
            tl: /* [] */0
          };
  }
}

function halfNW2SEDiagonal(inMatrix) {
  if (!inMatrix) {
    return Pervasives.failwith("error_halfNW2SEDiagonal");
  }
  var match = inMatrix.hd;
  if (!match) {
    return Pervasives.failwith("error_halfNW2SEDiagonal");
  }
  var tl = inMatrix.tl;
  if (tl) {
    return {
            hd: mainDiagonal(inMatrix),
            tl: halfNW2SEDiagonal(tl)
          };
  } else {
    return {
            hd: {
              hd: match.hd,
              tl: /* [] */0
            },
            tl: /* [] */0
          };
  }
}

function allDiagonal(inMatrix) {
  return Pervasives.$at(halfNW2SEDiagonal(inMatrix), Pervasives.$at(halfNW2SEDiagonal(transpose(inMatrix)), Pervasives.$at(halfNW2SEDiagonal(List.rev(inMatrix)), halfNW2SEDiagonal(transpose(List.rev(inMatrix))))));
}

function stringOfPlayer(input) {
  if (input) {
    return "Player2(Yellow)";
  } else {
    return "Player1(Red)";
  }
}

function stringOfListPlace(alop) {
  return "|" + (List.fold_right((function (str0, str1) {
                  return str0 + str1;
                }), List.map(stringOfPlace, alop), "") + "|\n");
}

function stringOfMatrix(inMatrix) {
  return List.fold_right((function (str0, str1) {
                return str0 + str1;
              }), List.map(stringOfListPlace, transpose(inMatrix)), "");
}

function stringOfState(param) {
  var inMatrix = param._1;
  var inStatus = param._0;
  if (typeof inStatus === "number") {
    return "Game: Draw" + stringOfMatrix(inMatrix);
  } else if (inStatus.TAG === /* Win */0) {
    return (
            inStatus._0 ? "Player2(Yellow)" : "Player1(Red)"
          ) + ("wins. \n" + stringOfMatrix(inMatrix));
  } else {
    return "Game is ongoing. It's " + ((
              inStatus._0 ? "Player2(Yellow)" : "Player1(Red)"
            ) + ("'s turn. \n" + stringOfMatrix(inMatrix)));
  }
}

function stringOfMove(inNum) {
  return "The player move in No." + (String(inNum._0) + " column");
}

function otherPlayer(param) {
  if (param) {
    return /* P1 */0;
  } else {
    return /* P2 */1;
  }
}

function initialState(s) {
  var boardDims = CS17SetupGame$Game_project.parseBoardDims(s);
  var boardHeight = CS17SetupGame$Game_project.getBoardHeight(boardDims);
  var boardWidth = CS17SetupGame$Game_project.getBoardWidth(boardDims);
  var repeatList = function (elem, num) {
    if (num !== 1) {
      return {
              hd: elem,
              tl: repeatList(elem, num - 1 | 0)
            };
    } else {
      return {
              hd: elem,
              tl: /* [] */0
            };
    }
  };
  var emptyColumn = repeatList(/* None */2, boardHeight);
  var initMatrix = repeatList(emptyColumn, boardWidth);
  return /* State */{
          _0: {
            TAG: /* Ongoing */1,
            _0: /* P1 */0
          },
          _1: initMatrix
        };
}

function legalMoves(inState) {
  var legalMovesHelper = function (_inMatrix, _num) {
    while(true) {
      var num = _num;
      var inMatrix = _inMatrix;
      if (!inMatrix) {
        return Pervasives.failwith("error: should input a matrix");
      }
      var match = inMatrix.hd;
      if (!match) {
        return Pervasives.failwith("error: should input a matrix");
      }
      var tail = inMatrix.tl;
      var hd = match.hd;
      if (!tail) {
        if (hd === /* None */2) {
          return {
                  hd: num,
                  tl: /* [] */0
                };
        } else {
          return /* [] */0;
        }
      }
      if (hd === /* None */2) {
        return {
                hd: num,
                tl: legalMovesHelper(tail, num + 1 | 0)
              };
      }
      _num = num + 1 | 0;
      _inMatrix = tail;
      continue ;
    };
  };
  return List.map((function (intElem) {
                return /* Move */{
                        _0: intElem
                      };
              }), legalMovesHelper(inState._1, 0));
}

function gameStatus(inState) {
  return inState._0;
}

function findNReplaceLastNoneInAColumn(alop, inplayer) {
  if (!alop) {
    return Pervasives.failwith("error: init matrix error. No empty matrix");
  }
  var hd = alop.hd;
  if (hd >= 2 && !alop.tl) {
    if (inplayer === /* P1 */0) {
      return {
              hd: /* Red */0,
              tl: /* [] */0
            };
    } else {
      return {
              hd: /* Yellow */1,
              tl: /* [] */0
            };
    }
  }
  var tl = alop.tl;
  if (hd === /* None */2 && List.hd(tl) !== /* None */2) {
    if (inplayer === /* P1 */0) {
      return {
              hd: /* Red */0,
              tl: tl
            };
    } else {
      return {
              hd: /* Yellow */1,
              tl: tl
            };
    }
  } else if (hd === /* None */2 && List.hd(tl) === /* None */2) {
    return {
            hd: /* None */2,
            tl: findNReplaceLastNoneInAColumn(tl, inplayer)
          };
  } else {
    return Pervasives.failwith("error: column is full. cannot put in");
  }
}

function nextStateHelper(inMatrix, inNum, whichPlayer) {
  if (!inMatrix) {
    return Pervasives.failwith("error: nextStateHelper");
  }
  var colHd = inMatrix.hd;
  if (colHd && colHd.hd >= 2 && !colHd.tl && !inMatrix.tl && inNum === 0) {
    if (whichPlayer === /* P1 */0) {
      return {
              hd: {
                hd: /* Red */0,
                tl: /* [] */0
              },
              tl: /* [] */0
            };
    } else {
      return {
              hd: {
                hd: /* Yellow */1,
                tl: /* [] */0
              },
              tl: /* [] */0
            };
    }
  }
  var colTl = inMatrix.tl;
  if (inNum !== 0) {
    return Pervasives.$at({
                hd: colHd,
                tl: /* [] */0
              }, nextStateHelper(colTl, inNum - 1 | 0, whichPlayer));
  } else {
    return {
            hd: findNReplaceLastNoneInAColumn(colHd, whichPlayer),
            tl: colTl
          };
  }
}

function isCloneList(_param) {
  while(true) {
    var param = _param;
    if (!param) {
      return false;
    }
    var match = param.tl;
    if (!match) {
      return false;
    }
    var tl = match.tl;
    var hd1 = match.hd;
    var hd0 = param.hd;
    if (!tl) {
      return hd0 === hd1;
    }
    if (hd0 !== hd1) {
      return false;
    }
    _param = tl;
    continue ;
  };
}

function isChainInAColumn(_inColumn, inPlace) {
  while(true) {
    var inColumn = _inColumn;
    if (!inColumn) {
      return false;
    }
    var match = inColumn.tl;
    if (!match) {
      return false;
    }
    var match$1 = match.tl;
    if (!match$1) {
      return false;
    }
    var match$2 = match$1.tl;
    if (!match$2) {
      return false;
    }
    var color0 = inColumn.hd;
    if (!match$2.tl) {
      if (color0 === inPlace) {
        return isCloneList(inColumn);
      } else {
        return false;
      }
    }
    if (color0 === inPlace) {
      if (isCloneList({
              hd: color0,
              tl: {
                hd: match.hd,
                tl: {
                  hd: match$1.hd,
                  tl: {
                    hd: match$2.hd,
                    tl: /* [] */0
                  }
                }
              }
            })) {
        return true;
      }
      _inColumn = List.tl(inColumn);
      continue ;
    }
    _inColumn = List.tl(inColumn);
    continue ;
  };
}

function isChainInAMatrixRough(_inMatrix, inplace) {
  while(true) {
    var inMatrix = _inMatrix;
    if (!inMatrix) {
      return Pervasives.failwith("error: isChainInAMatrixRough");
    }
    var coltl = inMatrix.tl;
    var aCol = inMatrix.hd;
    if (!coltl) {
      return isChainInAColumn(aCol, inplace);
    }
    if (isChainInAColumn(aCol, inplace)) {
      return true;
    }
    _inMatrix = coltl;
    continue ;
  };
}

function isChainInAMatrix(inMatrix, inplace) {
  if (isChainInAMatrixRough(inMatrix, inplace)) {
    return true;
  } else {
    return isChainInAMatrixRough(transpose(inMatrix), inplace);
  }
}

function checkWin(param) {
  var inplayer = param._0;
  if (typeof inplayer === "number") {
    return Pervasives.failwith("error: checkWin");
  }
  if (inplayer.TAG === /* Win */0) {
    return Pervasives.failwith("error: checkWin");
  }
  var inMatrix = param._1;
  if (inplayer._0) {
    return isChainInAMatrix(inMatrix, /* Yellow */1);
  } else {
    return isChainInAMatrix(inMatrix, /* Red */0);
  }
}

function nextState(inState, inMove) {
  var inPlayer = inState._0;
  if (typeof inPlayer === "number") {
    return inState;
  }
  if (inPlayer.TAG === /* Win */0) {
    return inState;
  }
  var noOfCol = inMove._0;
  var inMatrix = inState._1;
  var inPlayer$1 = inPlayer._0;
  var newMatrix = nextStateHelper(inMatrix, noOfCol, inPlayer$1);
  if (checkWin(/* State */{
          _0: {
            TAG: /* Ongoing */1,
            _0: inPlayer$1
          },
          _1: newMatrix
        })) {
    return /* State */{
            _0: {
              TAG: /* Win */0,
              _0: inPlayer$1
            },
            _1: newMatrix
          };
  } else if (List.mem(/* None */2, List.flatten(inMatrix))) {
    return /* State */{
            _0: {
              TAG: /* Ongoing */1,
              _0: inPlayer$1 ? /* P1 */0 : /* P2 */1
            },
            _1: nextStateHelper(inMatrix, noOfCol, inPlayer$1)
          };
  } else {
    return /* State */{
            _0: /* Draw */0,
            _1: nextStateHelper(inMatrix, noOfCol, inPlayer$1)
          };
  }
}

function moveOfString(str, myState) {
  var mov;
  try {
    mov = /* Move */{
      _0: Caml_format.caml_int_of_string(str) - 1 | 0
    };
  }
  catch (exn){
    mov = Pervasives.failwith("error: illegal move");
  }
  if (List.mem(mov, legalMoves(myState))) {
    return mov;
  } else {
    return Pervasives.failwith("error: illegal move");
  }
}

function estimateValue(param) {
  return Pervasives.failwith("not implenmented yet");
}

var Connect4 = {
  stringOfPlace: stringOfPlace,
  horzFlip: horzFlip,
  transpose: transpose,
  mainDiagonal: mainDiagonal,
  halfNW2SEDiagonal: halfNW2SEDiagonal,
  allDiagonal: allDiagonal,
  stringOfPlayer: stringOfPlayer,
  stringOfMatrix: stringOfMatrix,
  stringOfState: stringOfState,
  stringOfMove: stringOfMove,
  otherPlayer: otherPlayer,
  initialState: initialState,
  legalMoves: legalMoves,
  gameStatus: gameStatus,
  findNReplaceLastNoneInAColumn: findNReplaceLastNoneInAColumn,
  nextStateHelper: nextStateHelper,
  nextState: nextState,
  moveOfString: moveOfString,
  estimateValue: estimateValue
};

var MyGame = {
  stringOfPlayer: stringOfPlayer,
  stringOfState: stringOfState,
  stringOfMove: stringOfMove,
  initialState: initialState,
  legalMoves: legalMoves,
  gameStatus: gameStatus,
  nextState: nextState,
  moveOfString: moveOfString,
  estimateValue: estimateValue
};

exports.Connect4 = Connect4;
exports.MyGame = MyGame;
/* No side effect */
