// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var AIPlayer$Game_project = require("./AIPlayer.bs.js");
var Connect4$Game_project = require("./Connect4.bs.js");
var HumanPlayer$Game_project = require("./HumanPlayer.bs.js");

function Referee(MyGame, Player1, Player2) {
  var playGame = function (param) {
    try {
      var _s = Curry._1(MyGame.initialState, "5 6");
      while(true) {
        var s = _s;
        console.log(Curry._1(MyGame.stringOfState, s));
        var player = Curry._1(MyGame.gameStatus, s);
        if (typeof player === "number") {
          console.log("Draw...");
          return ;
        }
        if (player.TAG === /* Win */0) {
          console.log(Curry._1(MyGame.stringOfPlayer, player._0) + " wins!");
          return ;
        }
        var player$1 = player._0;
        console.log(Curry._1(MyGame.stringOfPlayer, player$1) + "'s turn.");
        var theMove = player$1 ? Curry._1(Player2.nextMove, s) : Curry._1(Player1.nextMove, s);
        console.log(Curry._1(MyGame.stringOfPlayer, player$1) + (" makes the move " + Curry._1(MyGame.stringOfMove, theMove)));
        _s = Curry._2(MyGame.nextState, s, theMove);
        continue ;
      };
    }
    catch (raw_message){
      var message = Caml_js_exceptions.internalToOCamlException(raw_message);
      if (message.RE_EXN_ID === "Failure") {
        console.log(message._1);
        return ;
      }
      throw message;
    }
  };
  return {
          CurrentGame: MyGame,
          playGame: playGame
        };
}

var $$let = AIPlayer$Game_project.AIPlayer({
      stringOfPlayer: Connect4$Game_project.Connect4.stringOfPlayer,
      stringOfState: Connect4$Game_project.Connect4.stringOfState,
      stringOfMove: Connect4$Game_project.Connect4.stringOfMove,
      initialState: Connect4$Game_project.Connect4.initialState,
      legalMoves: Connect4$Game_project.Connect4.legalMoves,
      gameStatus: Connect4$Game_project.Connect4.gameStatus,
      nextState: Connect4$Game_project.Connect4.nextState,
      moveOfString: Connect4$Game_project.Connect4.moveOfString,
      estimateValue: Connect4$Game_project.Connect4.estimateValue
    });

var partial_arg_nextMove = $$let.nextMove;

var partial_arg_stringOfPlayer = Connect4$Game_project.Connect4.stringOfPlayer;

var partial_arg_stringOfState = Connect4$Game_project.Connect4.stringOfState;

var partial_arg_stringOfMove = Connect4$Game_project.Connect4.stringOfMove;

var partial_arg_initialState = Connect4$Game_project.Connect4.initialState;

var partial_arg_legalMoves = Connect4$Game_project.Connect4.legalMoves;

var partial_arg_gameStatus = Connect4$Game_project.Connect4.gameStatus;

var partial_arg_nextState = Connect4$Game_project.Connect4.nextState;

var partial_arg_moveOfString = Connect4$Game_project.Connect4.moveOfString;

var partial_arg_estimateValue = Connect4$Game_project.Connect4.estimateValue;

var partial_arg = {
  stringOfPlayer: partial_arg_stringOfPlayer,
  stringOfState: partial_arg_stringOfState,
  stringOfMove: partial_arg_stringOfMove,
  initialState: partial_arg_initialState,
  legalMoves: partial_arg_legalMoves,
  gameStatus: partial_arg_gameStatus,
  nextState: partial_arg_nextState,
  moveOfString: partial_arg_moveOfString,
  estimateValue: partial_arg_estimateValue
};

var $$let$1 = AIPlayer$Game_project.AIPlayer({
      stringOfPlayer: Connect4$Game_project.Connect4.stringOfPlayer,
      stringOfState: Connect4$Game_project.Connect4.stringOfState,
      stringOfMove: Connect4$Game_project.Connect4.stringOfMove,
      initialState: Connect4$Game_project.Connect4.initialState,
      legalMoves: Connect4$Game_project.Connect4.legalMoves,
      gameStatus: Connect4$Game_project.Connect4.gameStatus,
      nextState: Connect4$Game_project.Connect4.nextState,
      moveOfString: Connect4$Game_project.Connect4.moveOfString,
      estimateValue: Connect4$Game_project.Connect4.estimateValue
    });

var R1 = (function (param) {
      var playGame = function (param$1) {
        try {
          var _s = Curry._1(partial_arg_initialState, "5 6");
          while(true) {
            var s = _s;
            console.log(Curry._1(partial_arg_stringOfState, s));
            var player = Curry._1(partial_arg_gameStatus, s);
            if (typeof player === "number") {
              console.log("Draw...");
              return ;
            }
            if (player.TAG === /* Win */0) {
              console.log(Curry._1(partial_arg_stringOfPlayer, player._0) + " wins!");
              return ;
            }
            var player$1 = player._0;
            console.log(Curry._1(partial_arg_stringOfPlayer, player$1) + "'s turn.");
            var theMove = player$1 ? Curry._1(param.nextMove, s) : Curry._1(partial_arg_nextMove, s);
            console.log(Curry._1(partial_arg_stringOfPlayer, player$1) + (" makes the move " + Curry._1(partial_arg_stringOfMove, theMove)));
            _s = Curry._2(partial_arg_nextState, s, theMove);
            continue ;
          };
        }
        catch (raw_message){
          var message = Caml_js_exceptions.internalToOCamlException(raw_message);
          if (message.RE_EXN_ID === "Failure") {
            console.log(message._1);
            return ;
          }
          throw message;
        }
      };
      return {
              CurrentGame: partial_arg,
              playGame: playGame
            };
    })({
      PlayerGame: $$let$1.PlayerGame,
      nextMove: $$let$1.nextMove,
      playerName: $$let$1.playerName
    });

var $$let$2 = HumanPlayer$Game_project.HumanPlayer({
      stringOfPlayer: Connect4$Game_project.Connect4.stringOfPlayer,
      stringOfState: Connect4$Game_project.Connect4.stringOfState,
      stringOfMove: Connect4$Game_project.Connect4.stringOfMove,
      initialState: Connect4$Game_project.Connect4.initialState,
      legalMoves: Connect4$Game_project.Connect4.legalMoves,
      gameStatus: Connect4$Game_project.Connect4.gameStatus,
      nextState: Connect4$Game_project.Connect4.nextState,
      moveOfString: Connect4$Game_project.Connect4.moveOfString,
      estimateValue: Connect4$Game_project.Connect4.estimateValue
    });

var partial_arg_nextMove$1 = $$let$2.nextMove;

var partial_arg_stringOfPlayer$1 = Connect4$Game_project.Connect4.stringOfPlayer;

var partial_arg_stringOfState$1 = Connect4$Game_project.Connect4.stringOfState;

var partial_arg_stringOfMove$1 = Connect4$Game_project.Connect4.stringOfMove;

var partial_arg_initialState$1 = Connect4$Game_project.Connect4.initialState;

var partial_arg_legalMoves$1 = Connect4$Game_project.Connect4.legalMoves;

var partial_arg_gameStatus$1 = Connect4$Game_project.Connect4.gameStatus;

var partial_arg_nextState$1 = Connect4$Game_project.Connect4.nextState;

var partial_arg_moveOfString$1 = Connect4$Game_project.Connect4.moveOfString;

var partial_arg_estimateValue$1 = Connect4$Game_project.Connect4.estimateValue;

var partial_arg$1 = {
  stringOfPlayer: partial_arg_stringOfPlayer$1,
  stringOfState: partial_arg_stringOfState$1,
  stringOfMove: partial_arg_stringOfMove$1,
  initialState: partial_arg_initialState$1,
  legalMoves: partial_arg_legalMoves$1,
  gameStatus: partial_arg_gameStatus$1,
  nextState: partial_arg_nextState$1,
  moveOfString: partial_arg_moveOfString$1,
  estimateValue: partial_arg_estimateValue$1
};

var $$let$3 = HumanPlayer$Game_project.HumanPlayer({
      stringOfPlayer: Connect4$Game_project.Connect4.stringOfPlayer,
      stringOfState: Connect4$Game_project.Connect4.stringOfState,
      stringOfMove: Connect4$Game_project.Connect4.stringOfMove,
      initialState: Connect4$Game_project.Connect4.initialState,
      legalMoves: Connect4$Game_project.Connect4.legalMoves,
      gameStatus: Connect4$Game_project.Connect4.gameStatus,
      nextState: Connect4$Game_project.Connect4.nextState,
      moveOfString: Connect4$Game_project.Connect4.moveOfString,
      estimateValue: Connect4$Game_project.Connect4.estimateValue
    });

var R2Human2Human = (function (param) {
      var playGame = function (param$1) {
        try {
          var _s = Curry._1(partial_arg_initialState$1, "5 6");
          while(true) {
            var s = _s;
            console.log(Curry._1(partial_arg_stringOfState$1, s));
            var player = Curry._1(partial_arg_gameStatus$1, s);
            if (typeof player === "number") {
              console.log("Draw...");
              return ;
            }
            if (player.TAG === /* Win */0) {
              console.log(Curry._1(partial_arg_stringOfPlayer$1, player._0) + " wins!");
              return ;
            }
            var player$1 = player._0;
            console.log(Curry._1(partial_arg_stringOfPlayer$1, player$1) + "'s turn.");
            var theMove = player$1 ? Curry._1(param.nextMove, s) : Curry._1(partial_arg_nextMove$1, s);
            console.log(Curry._1(partial_arg_stringOfPlayer$1, player$1) + (" makes the move " + Curry._1(partial_arg_stringOfMove$1, theMove)));
            _s = Curry._2(partial_arg_nextState$1, s, theMove);
            continue ;
          };
        }
        catch (raw_message){
          var message = Caml_js_exceptions.internalToOCamlException(raw_message);
          if (message.RE_EXN_ID === "Failure") {
            console.log(message._1);
            return ;
          }
          throw message;
        }
      };
      return {
              CurrentGame: partial_arg$1,
              playGame: playGame
            };
    })({
      PlayerGame: $$let$3.PlayerGame,
      nextMove: $$let$3.nextMove,
      playerName: $$let$3.playerName
    });

var $$let$4 = HumanPlayer$Game_project.HumanPlayer({
      stringOfPlayer: Connect4$Game_project.Connect4.stringOfPlayer,
      stringOfState: Connect4$Game_project.Connect4.stringOfState,
      stringOfMove: Connect4$Game_project.Connect4.stringOfMove,
      initialState: Connect4$Game_project.Connect4.initialState,
      legalMoves: Connect4$Game_project.Connect4.legalMoves,
      gameStatus: Connect4$Game_project.Connect4.gameStatus,
      nextState: Connect4$Game_project.Connect4.nextState,
      moveOfString: Connect4$Game_project.Connect4.moveOfString,
      estimateValue: Connect4$Game_project.Connect4.estimateValue
    });

var partial_arg_nextMove$2 = $$let$4.nextMove;

var partial_arg_stringOfPlayer$2 = Connect4$Game_project.Connect4.stringOfPlayer;

var partial_arg_stringOfState$2 = Connect4$Game_project.Connect4.stringOfState;

var partial_arg_stringOfMove$2 = Connect4$Game_project.Connect4.stringOfMove;

var partial_arg_initialState$2 = Connect4$Game_project.Connect4.initialState;

var partial_arg_legalMoves$2 = Connect4$Game_project.Connect4.legalMoves;

var partial_arg_gameStatus$2 = Connect4$Game_project.Connect4.gameStatus;

var partial_arg_nextState$2 = Connect4$Game_project.Connect4.nextState;

var partial_arg_moveOfString$2 = Connect4$Game_project.Connect4.moveOfString;

var partial_arg_estimateValue$2 = Connect4$Game_project.Connect4.estimateValue;

var partial_arg$2 = {
  stringOfPlayer: partial_arg_stringOfPlayer$2,
  stringOfState: partial_arg_stringOfState$2,
  stringOfMove: partial_arg_stringOfMove$2,
  initialState: partial_arg_initialState$2,
  legalMoves: partial_arg_legalMoves$2,
  gameStatus: partial_arg_gameStatus$2,
  nextState: partial_arg_nextState$2,
  moveOfString: partial_arg_moveOfString$2,
  estimateValue: partial_arg_estimateValue$2
};

var $$let$5 = AIPlayer$Game_project.AIPlayer({
      stringOfPlayer: Connect4$Game_project.Connect4.stringOfPlayer,
      stringOfState: Connect4$Game_project.Connect4.stringOfState,
      stringOfMove: Connect4$Game_project.Connect4.stringOfMove,
      initialState: Connect4$Game_project.Connect4.initialState,
      legalMoves: Connect4$Game_project.Connect4.legalMoves,
      gameStatus: Connect4$Game_project.Connect4.gameStatus,
      nextState: Connect4$Game_project.Connect4.nextState,
      moveOfString: Connect4$Game_project.Connect4.moveOfString,
      estimateValue: Connect4$Game_project.Connect4.estimateValue
    });

var R3Human2AI = (function (param) {
      var playGame = function (param$1) {
        try {
          var _s = Curry._1(partial_arg_initialState$2, "5 6");
          while(true) {
            var s = _s;
            console.log(Curry._1(partial_arg_stringOfState$2, s));
            var player = Curry._1(partial_arg_gameStatus$2, s);
            if (typeof player === "number") {
              console.log("Draw...");
              return ;
            }
            if (player.TAG === /* Win */0) {
              console.log(Curry._1(partial_arg_stringOfPlayer$2, player._0) + " wins!");
              return ;
            }
            var player$1 = player._0;
            console.log(Curry._1(partial_arg_stringOfPlayer$2, player$1) + "'s turn.");
            var theMove = player$1 ? Curry._1(param.nextMove, s) : Curry._1(partial_arg_nextMove$2, s);
            console.log(Curry._1(partial_arg_stringOfPlayer$2, player$1) + (" makes the move " + Curry._1(partial_arg_stringOfMove$2, theMove)));
            _s = Curry._2(partial_arg_nextState$2, s, theMove);
            continue ;
          };
        }
        catch (raw_message){
          var message = Caml_js_exceptions.internalToOCamlException(raw_message);
          if (message.RE_EXN_ID === "Failure") {
            console.log(message._1);
            return ;
          }
          throw message;
        }
      };
      return {
              CurrentGame: partial_arg$2,
              playGame: playGame
            };
    })({
      PlayerGame: $$let$5.PlayerGame,
      nextMove: $$let$5.nextMove,
      playerName: $$let$5.playerName
    });

Curry._1(R3Human2AI.playGame, undefined);

exports.Referee = Referee;
exports.R1 = R1;
exports.R2Human2Human = R2Human2Human;
exports.R3Human2AI = R3Human2AI;
/* R1 Not a pure module */
